name: PHPUnit Tests

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-18.04

    container:
      image:  prooph/composer:7.2

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate application key
        run: php artisan key:generate
      - name: Create database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate
      - name: Run tests
        run: vendor/bin/phpunit

