name: PHPUnit Tests

on: [pull_request, push]

jobs:
  run-tests:
    runs-on: ubuntu-18.04

    container:
      image:  prooph/composer:7.2

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate application key
        run: |
          echo "APP_KEY=" > .env
          php artisan key:generate
      - name: Create folders
        run: |
          mkdir -p bootstrap/cache
      - name: Run tests
        run: vendor/bin/phpunit

